title: Malav Shah # your name (or website title) here
logo: "/images/profile2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student, Cyclist, Motorcyclist
  <br><br>
  <a href="https://www.linkedin.com/in/malav-shah-11b532124/">Linked In</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
